### ISSUE TITLE
Related to the forum: Can't link events to calendar

### ISSUE THREAD

**Issue by serjeason** [jsrn/cove.sugeworld.com#9]
As per my post on the Events Board;

'OOC: This works on my Gregor Eason account but on my Serj Eason account the numbers aren't clickable on the calendar...! :O So I have added the Event with Serj on the Board but added the event on the Calendar with the GE account (so its not linked).'

**Comment by jsrn** [comment]
I've set it so that regular members should be able to post events to the calendar. Can you please check it and close this issue if it's all good?

**Comment by serjeason** [comment]
Yep! It's all good. Thanks man.
